### 测试插入文章
POST http://localhost:8080/api/v1/news/
Content-Type: application/json

{
  "Title": "PanshiCMS API功能开发完成",
  "Summary": "现在我们可以通过API管理文章了。",
  "Content": "<p>这是一个重要的里程碑。</p>",
  "PublishDate": "2025-08-02T10:30:00Z",
  "Slug": "panshi-cms-api-done"
}

<> 2025-08-04T232908.200.json

### 初始化管理员
POST http://localhost:8080/init
Content-Type: application/json

{
    "username": "admin",
    "password": "password"
}

<> 2025-08-04T233827.200.json

### 登陆

POST http://localhost:8080/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

<> 2025-08-04T233926.200.json
<> 2025-08-04T233858.200.json

### 应当拦截
# curl http://localhost:8080/api/v1/news
GET http://localhost:8080/api/v1/news/

<> 2025-08-04T233912.401.json

### 应当获取文章

# curl -H "Authorization: Bearer <YOUR_TOKEN>" http://localhost:8080/api/v1/news
GET http://localhost:8080/api/v1/news/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQ5MjY3NjYsInN1YiI6MX0.4a5khmmhg_dqPyZKW5qqWDJ3xEjbl4yKJy-83WPjB_o

<> 2025-08-04T234206.200.json
<> 2025-08-04T233937.401.json

### services测试

POST http://localhost:8080/api/v1/services/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTQ5MjY3NjYsInN1YiI6MX0.4a5khmmhg_dqPyZKW5qqWDJ3xEjbl4yKJy-83WPjB_o
Content-Type: application/json

{
  "Title": "核心技术咨询",
  "Summary": "提供专业的Go语言后端架构咨询服务。",
  "Content": "详情...",
  "Slug": "go-backend-consulting"
}





